x-app-env: &app-env
  env_file:
    - .env
    - .env.docker

services:
  # -----------------------
  # DATABASE + REDIS
  # -----------------------
  postgres:
    image: postgres:15
    restart: unless-stopped
    container_name: flowmesh-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flowmesh
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    restart: unless-stopped
    container_name: flowmesh-redis

  # -----------------------
  # LOGGING STACK
  # -----------------------
  loki:
    image: grafana/loki:3.0.0
    restart: unless-stopped
    container_name: loki
    volumes:
      - ./loki-config.yaml:/mnt/config/loki-config.yaml
      - ./data:/tmp
    command: -config.file=/mnt/config/loki-config.yaml

  promtail:
    image: grafana/promtail:3.0.0
    restart: unless-stopped
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/mnt/config/promtail-config.yaml
      - /var/log:/var/log
    depends_on:
      - loki
    command: -config.file=/mnt/config/promtail-config.yaml

  grafana:
    image: grafana/grafana-oss
    restart: unless-stopped
    container_name: grafana
    ports:
      - "127.0.0.1:3099:3000"
    depends_on:
      - loki

  # -----------------------
  # API
  # -----------------------
  flowmesh-api:
    <<: *app-env
    build:
      context: .
      dockerfile: src/api/DockerFile
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: flowmesh-api
    restart: unless-stopped
    ports:
      - "127.0.0.1:5555:5555"
    depends_on:
      - postgres
      - redis
      - loki

  # -----------------------
  # WORKERS
  # -----------------------
  flowmesh-payment-worker:
    <<: *app-env
    build:
      context: .
      dockerfile: src/workers/DockerFile
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: flowmesh-payment-worker
    restart: unless-stopped
    command: node dist/src/workers/paymentWorker.js
    depends_on:
      - postgres
      - redis
      - loki

  flowmesh-shipment-worker:
    <<: *app-env
    build:
      context: .
      dockerfile: src/workers/DockerFile
      args:
        DATABASE_URL: ${DATABASE_URL}
    container_name: flowmesh-shipment-worker
    restart: unless-stopped
    command: node dist/src/workers/shipmentWorker.js
    depends_on:
      - postgres
      - redis
      - loki

# -----------------------
# VOLUMES
# -----------------------
volumes:
  postgres_data:
