x-app-env: &app-env
  env_file:
    - .env
    - .env.docker

services:
  # -----------------------
  # DATABASE + REDIS
  # -----------------------
  postgres:
    image: postgres:15
    container_name: flowmesh-postgres
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flowmesh
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: flowmesh-redis
    ports:
      - "6379:6379"

  # -----------------------
  # LOGGING STACK
  # -----------------------
  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    volumes:
      - ./loki-config.yaml:/mnt/config/loki-config.yaml
      - ./data:/tmp
    ports:
      - "3100:3100"
    command: -config.file=/mnt/config/loki-config.yaml

  promtail:
    image: grafana/promtail:3.0.0
    container_name: promtail
    volumes:
      - ./promtail-config.yaml:/mnt/config/promtail-config.yaml
      - /var/log:/var/log
    depends_on:
      - loki
    command: -config.file=/mnt/config/promtail-config.yaml

  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    ports:
      - "3099:3000"
    depends_on:
      - loki

  # -----------------------
  # API
  # -----------------------
  flowmesh-api:
    <<: *app-env
    build:
      context: .
      dockerfile: src/api/DockerFile
    container_name: flowmesh-api
    ports:
      - "5555:5555"
    depends_on:
      - postgres
      - redis
      - loki

  # -----------------------
  # WORKERS
  # -----------------------
  flowmesh-payment-worker:
    <<: *app-env
    build:
      context: .
      dockerfile: src/workers/DockerFile
    container_name: flowmesh-payment-worker
    command: node dist/src/workers/paymentWorker.js
    depends_on:
      - postgres
      - redis
      - loki

  flowmesh-shipment-worker:
    <<: *app-env
    build:
      context: .
      dockerfile: src/workers/DockerFile
    container_name: flowmesh-shipment-worker
    command: node dist/src/workers/shipmentWorker.js
    depends_on:
      - postgres
      - redis
      - loki

# -----------------------
# VOLUMES
# -----------------------
volumes:
  postgres_data:
